src/client.ts
src/open-feature.ts
src/types.ts
test/client.spec.ts
test/hooks.spec.ts
test/open-feature.spec.ts

Adds hooks, as per spec, along with tests.
Closes: https://github.com/open-feature/node-sdk/issues/7

Implement hooks

---

README.md

Tested toe SDK locally (CommonJS and ESM), looks good... so I'm going to add an "experimental" and "alpha" badge and remove the placeholder warning.

Remove stub warning, adding badges

---

src/client.ts
src/types.ts
test/hooks.spec.ts

Change FlagValue to FlagValueType

---

README.md

Add alpha checklist to readme.

Add alpha checklist

---

.github/workflows/publish-dev.yaml
src/no-op-provider.ts

Allow version update with branch protection

Allow version update with branch protection

---

.github/workflows/publish-dev.yaml
package-lock.json
package.json

Fix branch protection build issue

---

.github/workflows/pr-checks.yaml
.github/workflows/publish-dev.yaml
README.md

Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>

Add Codecov upload step

---

.eslintrc.json
package-lock.json
package.json

Fix lint issue

---

.github/workflows/experimental-release.yaml
.github/workflows/lint-pr.yml
.github/workflows/pr-checks.yaml
.github/workflows/release.yml

Adds workflow consistent with other SDKs

Add release workflow

---

.github/workflows/release.yml

chore: Fix ref in workflow

---

.github/workflows/release.yml

chore: Move tag

---

.github/workflows/release.yml

chore: Use publish activity

---

.github/workflows/release.yml

fix: Use release hook

---

.github/workflows/release.yml

chore: Use create type

---

.github/workflows/release.yml

chore: Add tags

---

.github/workflows/release.yml

Release with manual tags

---

.github/workflows/release.yml

Manual versioning

---

.github/workflows/release-please.yml

fix: Fix publish command

---

.github/workflows/experimental-release.yaml

chore: Adding experimental tag

---

.github/workflows/coverage.yml
.github/workflows/publish-experimental.yml

chore: Add experimental publish

---

.github/workflows/publish-experimental.yml

Fix script

---

package.json

Add current version script

---

README.md

docs: add overview of OpenFeature to the readme

---

release-please-config.json

chore: bumpMinorPreMajor + bumpPatchForMinorPreMajor

---

test/hooks.spec.ts

Improving the context merge test (4.3.4) to include all possible context stages.
No functional changes.

chore: Improve context merge test

---

test/client.spec.ts

chore: improve merging test to include the before hook

---

src/client.ts
src/types.ts
test/client.spec.ts

Adding this for consistency with other SDKs.

feat: add client context mutation

---

src/client.ts
src/open-feature.ts
src/types.ts

chore: move jsdoc to interfaces

---

.eslintrc.json
src/client.ts
src/no-op-transaction-context-propagator.ts
src/open-feature.ts
src/types.ts
test/client.spec.ts
test/open-feature.spec.ts

feat: add transaction propagation

---

README.md
tsconfig.json

chore: change target to es2015

---

README.md

Closes: https://github.com/open-feature/js-sdk/issues/279

chore: update spec badge

---

release-please-config.json

- Hopefully fixes the change log of the v1 release.

chore: bump bootstrap sha

---

CONTRIBUTING.md
README.md

- Adds a contributing doc to the repo
- Adds an OpenSSF badge to the readme

docs: add contributing doc

---

package-lock.json
package.json

chore: bump flagd provider version

---

README.md

- Adds a link to the getting started doc
- Adds a link to the API docs
- Adds a link to the list of providers
- Adds a link to the list of hooks
- Adds an explication for how hooks work.
Fixes #351 

docs: improved the readme

---

src/types.ts

As per: https://github.com/open-feature/spec/blob/7ed7442c40d4e766424671258846b21a96adda70/specification/types.md#resolution-details

feat: add STATIC, CACHED reasons

---

packages/client/src/client.ts
packages/client/src/open-feature.ts
packages/client/src/types.ts

This PR removes the context from the client's API (as per draft spec).

fix!: remove context from client interfaces

---

README.md
packages/server/README.md

docs: fix broken link

---

packages/client/src/client.ts
packages/client/src/open-feature.ts

Fix import cycle caused by previous export/import from barrel file.

fix: import cycle

---

packages/client/test/client.spec.ts
packages/client/test/events.spec.ts

- added tests based on [spec PR](https://github.com/open-feature/spec/pull/171)
Fixes #407

test: add events tests for web-sdk

---

packages/client/README.md

Technically we already released 0.3.11, but I think it's good to release a totally new major(really minor b/c we are under 1) version. I've also removed the "experimental" from the readme.

feat: release first non-experimental version

---

packages/server/README.md
release-please-config.json

- update the server-side readme using the new template

docs: update server-side sdk readme

---

packages/client/README.md
release-please-config.json

- updates the web sdk readme to follow the new template

docs: update web sdk readme

---

packages/react/src/use-feature-flag.ts

Implements the change proposed [here](https://github.com/open-feature/js-sdk/pull/546#discussion_r1302922403) for the useFeatureFlag hook.
Instead of writing the flag to the hook state and updating it on events, the flag is just always evaluated. 
This prevents us from cache inconsistencies.
One thing I had to do was adding a forceUpdate which forces react to rerender and by this returns the new flag value when an event occurs.

feat: do not add feature flags to state

---

packages/client/test/client.spec.ts
packages/client/test/events.spec.ts
packages/client/test/open-feature.spec.ts
packages/server/test/client.spec.ts
packages/server/test/events.spec.ts
packages/server/test/open-feature.spec.ts
packages/shared/src/open-feature.ts

- adds setProviderAndWait method
Fixes #576
I'll update the READMEs with examples once the feature has been released.

feat: add support for a blocking setProvider

---

package-lock.json
packages/server/README.md
packages/server/package.json
release-please-config.json

Publishing under new name, with updated bootstrap SHA. Not a real fix, will correct that in release notes.

fix: publish as @openfeature/server-sdk

---

packages/server/README.md
packages/server/package.json

fix: package in readme installs/examples

---

packages/shared/tsconfig.json

- remove unused source file from tsconfig

chore: remove unused source file from tsconfig

---

packages/client/README.md
packages/server/README.md
packages/shared/README.md

fix: api docs links

---

packages/client/README.md
packages/server/README.md

- add @openfeature/core to yarn install instructions

docs: extend yarn docs

---

release-please-config.json

- remove the prerelease badge from the Release Please config

chore: remove prerelease badge from release please config

---

.github/workflows/release-please.yml

SBOM generation failed because I forgot the checkout step.
This adds it.

fix: missing checkout step in sbom generation

---

package-lock.json
package.json
packages/server/e2e/step-definitions/jest.config.ts

chore: update flagd-provider

---

renovate.json

- enables renovate best practices
The current configuration seems to be invalid. This PR updates Renovate to use best practices recommended by the Renovate team.
https://docs.renovatebot.com/presets-config/#configbest-practices

chore: update renovate to use best practices

---

packages/nest/src/open-feature.module.ts
packages/nest/src/shutdown.service.ts

- adds a way to gracefully shutdown providers in the Nest SDK

feat: add shutdown service

---

packages/nest/src/open-feature.module.ts
packages/nest/src/shutdown.service.ts
packages/nest/test/open-feature-sdk.spec.ts
packages/nest/test/open-feature.module.spec.ts

Adds options for logger, event handlers and hooks to Nest SDK initialization.
This change makes the SDK completely configurable during the initialization without the need to explicitly call the OpenFeature API.
Relates to #705

feat: add logger, event handlers and hooks to nest sdk

---

jest.config.ts

- enables the Jest GitHub reporter
https://jestjs.io/docs/configuration#github-actions-reporter

ci: configure GitHub jest reporter

---

packages/nest/README.md
packages/nest/src/feature.decorator.ts
packages/nest/src/open-feature.module.ts
packages/nest/test/fixtures.ts
packages/nest/test/open-feature-sdk.spec.ts
packages/nest/test/open-feature.module.spec.ts
packages/nest/test/test-app.ts

- adds support for domains
- removes named clients
relates to https://github.com/open-feature/spec/pull/229

feat(nestjs)!: add domains

---

packages/react/README.md
packages/react/src/provider.tsx

- adds support for domains
- removes named clients

feat!: use "domain" instead of "clientName"

---

packages/shared/src/evaluation/evaluation.ts

Adds STALE pre-defined reason, re-orders reasons in source to match spec.

feat: add STALE pre-defined reason

---

packages/react/src/evaluation/use-feature-flag.ts
packages/react/test/evaluation.spec.tsx

- fixes issue where invocation hooks were not called in the React SDK
- adds associated tests 
Fixes: https://github.com/open-feature/js-sdk/issues/914

fix: invocation hooks not called

---

packages/client/README.md
packages/server/README.md

- adds tip to node.js about web
- adds tip to web about node.js
Related to the PR opened by @dabeeeenster.
https://github.com/open-feature/openfeature.dev/pull/552

docs: add tip about supported usage in the install section

---

package-lock.json
packages/client/package.json

fix(web-sdk): pin core version to 1.3.0

---

packages/angular/projects/angular-sdk/package.json

Copy license to package correctly

fix: copy license to package correctly

---

packages/web/package.json

Bump core version to match the latest.

chore(web): bump core peer version

---

packages/angular/projects/angular-sdk/package.json

chore: add npm keywords for angular

---

packages/react/src/evaluation/use-feature-flag.ts

- maintains a reference to the latest evaluation details.
The change to optimize the rendering behavior was comparing a stale value.
https://github.com/open-feature/js-sdk/pull/987
This PR adds a [mutable ref](https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables) that's updated every time the evaluation details are updated.
This was manually tested. Unit tests will follow.

fix: failure to re-render on changes

---

packages/angular/package.json

Fixes typo in angular sdk version check for publishing.

fix(angular): fix version check for angular publishing

---

packages/angular/projects/angular-sdk/package.json

- adds package.json description

fix(angular): add package description

---

packages/react/README.md
packages/server/README.md
packages/web/README.md

- adds tracking to all relevant READMEs

docs: add tracking sections

---

.github/workflows/release-please.yml

Adds missing permissions
https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions

ci: add id token write permissions

---

packages/angular/projects/angular-sdk/package.json

- adds this new feature
Fixes #1234523

chore(angular): add repository to package.json

---

packages/shared/src/index.ts

Exports the recently added telemetry functionality from code.
https://github.com/open-feature/js-sdk/pull/1120

fix: export missing telemetry functionality

---

package.json

Somehow we forgot to add this module here.

chore: add nest to test script

---

packages/angular/projects/angular-sdk/README.md

Adds docs for setting evaluation context in angular

feat(angular): add docs for setting evaluation context in angular

---

package-lock.json
packages/nest/README.md
packages/nest/package.json

Adds support for NestJS 11.
Fixes #1173

chore(nest): allow nestjs version 11
