open-feature/js-sdk

.eslintrc.json, .prettierrc, package-lock.json, package.json, src/client.ts, src/constants.ts, src/index.ts, src/no-op-provider.ts, src/open-feature.ts, src/types.ts, test/client.spec.ts, test/index.spec.ts, test/open-feature.spec.ts
First pass at API and client functionality, not including hooks and evaluation context details.
Added applicable tests based on spec requirements: 
```
PASS  test/open-feature.spec.ts
OpenFeature
Requirement 1.1
✓ should be global singleton (2 ms)
Requirement 1.2
✓ should be set provider
Requirement 1.3
✓ should allow addition of hooks
Requirement 1.4
✓ should implement a hook accessor
Requirement 1.5
✓ should implement a client factory (1 ms)
PASS  test/client.spec.ts
OpenFeatureClient
Requirement 1.6
✓ should allow addition of hooks
Requirement 1.7, 1.8
flag evaluation
getBooleanValue
✓ should return boolean, and call boolean resolver (2 ms)
getStringValue
✓ should return string, and call string resolver
getNumberValue
✓ should return number, and call number resolver (1 ms) …
```
=> Add api, client

.eslintrc.json, jest.config.ts, package-lock.json, package.json, src/client.ts, src/index.ts, src/no-op-provider.ts, src/open-feature.ts, test/client.spec.ts, test/open-feature.spec.ts
https://github.com/microsoft/TypeScript/issues/16577
https://github.com/microsoft/TypeScript/issues/40878
TLDR: ESM imports REQUIRE a file extension. Typescript does not. Typescript also does not "rewrite" the compiled output to have the correct .js extension (and seems like it never will  :angry: :angry: :angry:). However, TS "ignores" the file extension when importing files (ie: `import "./constants"` is the same as `import "./constants.js"`).
... so I've added a lint rule that forces us to always add `.js` in our TS import statements, which practically solves the problem and makes our ESM output valid.
Relevant note from @dyladan :
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs
Seems like this is basically the recommendation from the TS devs at this …
=> Fix issues with extensions in ESM

src/types.ts, test/hooks.spec.ts
Previously, hooks HAD to be async. We want to support async hooks, but I think that's really an edge case. I've added type-support for sync hooks, and made all the existing hooks in the test suite sync. I also added a new test section specifically for async hooks.
=> Add support for sync hooks

src/client.ts, src/no-op-provider.ts, src/open-feature.ts, src/types.ts, test/client.spec.ts, test/hooks.spec.ts, test/open-feature.spec.ts
Removes refs to provider, client in `hookContext` (replacing with metadata), and provider accessor from API.
=> Remove provider/client refs, add metadata

src/types.ts, test/client.spec.ts
Add support for `Date` and `JSON objects` in the evaluation context as
defined in Requirement 3.1 of the Evaulation Context specification
refs #23
=> feat: add support for Date and JSON objects

src/open-feature.ts
Very small change to remove protected constructor which we only needed since the class was previously exported and we didn't want people instantiating it. Now since it's not exported we can use the default constructor.
=> Removing constructor, not exported anymore

src/errors/index.ts
The `OpenFeatureError` abstract class is not public and is used only internally.
It could be great to let people developing **providers** and **hooks** extend it to have the right format when creating new types of errors.
Without that we can only use these errors :
- `FlagNotFoundError`
- `ParseError`
- `TypeMismatchError`
=> Export the abstract error

test/no-op.spec.ts
=> fix: Add no-op tests

src/open-feature.ts
Provider is a conditional type. Using it here is incorrect because we are basically saying that we know the provider to be only one of the two possible types expressed [here](https://github.com/open-feature/node-sdk/blob/a37d0fcd855579e3cdac12e2e13955899f74521b/src/types.ts#L170). This method needs to handle both. The simple solution is to allow this method to handle either provider type, not the conditional type.
Closes: https://github.com/open-feature/node-sdk/issues/119
I tested this with a local publish BTW, it seems to fix @thomaspoignant 's issue.
=> fix: Fixing error with setProvider type

src/client.ts, src/open-feature.ts, src/types.ts, test/client.spec.ts, test/hooks.spec.ts
- remove context transformer
- adds provider hooks
- updates to new hook ordering
- updates tests accordingly, included referenced spec numbers
=> feat!: remove ctx transformer, add provider hooks

README.md, src/types.ts
=> feat!: remove flag evaluation options from the provider interface

src/client.ts, src/index.ts, src/logger.ts, src/open-feature.ts, src/types.ts, test/client.spec.ts, test/hooks.spec.ts, test/logger.spec.ts, test/no-op.spec.ts, test/open-feature.spec.ts
Features include:
- A default logger that writes warning and errors to the console.
- A safe logger that will wrap user providers loggers to ensure stability
- Global logger can be updated with a custom logger
- Clients can be updated with a customer logger
- Custom client loggers override global loggers
=> feat: add logger

.eslintrc.json, package-lock.json, package.json, src/client.ts, src/logger.ts, src/open-feature.ts, src/types.ts, test/client.spec.ts, test/hooks.spec.ts, test/logger.spec.ts, test/open-feature.spec.ts
Updated various touchpoints in the global API and client to be chainable methods. This is a breaking change that is intended to provide a more consistent developer experience.
=> feat!: convert to chainable methods

src/client.ts, src/no-op-provider.ts, src/types.ts, test/client.spec.ts, test/tsconfig.json
- restricts generic args on object resolver (`T` is now `T extends JsonValue`)
- adds optional generic args for string/number resolver for unions of string/number literals
=> feat!: improve generic type accuracy

.github/workflows/pr-checks.yaml, .gitignore, .gitmodules, README.md, integration/features/.gitignore, integration/step-definitions/evaluation.spec.ts, integration/step-definitions/jest.config.ts, integration/step-definitions/setup.ts, integration/step-definitions/tsconfig.json, jest.config.ts, package-lock.json, package.json
Add integration tests. Basically a JS version of: https://github.com/open-feature/java-sdk/pull/77
=> chore: add integration tests

.eslintrc.json, .github/workflows/release-please.yml, .gitignore, package-lock.json, package.json, src/index.ts, src/open-feature.ts, src/types.ts, tsconfig.json
This PR
Generates documentation based on TypeScript types and deploys the docs using GH pages.
How to test
This was tested in a fork. The generated GH page can be seen [here](https://beeme1mr.github.io/js-sdk/).
Signed-off-by: Michael Beemer [beeme1mr@users.noreply.github.com](mailto:beeme1mr@users.noreply.github.com)
=> feat: add typedoc support

README.md
This adds more usage doc to give a terse API overview. It also adds a link to docs.openefeature.dev, which is where we really want to push people for thorough doc.
=> chore: improve usage doc, refer to docs

.github/workflows/publish-experimental.yml, CODEOWNERS
@beeme1mr  I'm not sure if this was always the case, or something changed, but there's a minor bug in the experimental publish that caused it to be labeled with the wrong SHA.
The contents are correct, but the SHA would actually be the SHA of the HEAD of main (which is a bit confusing). This fixes that to be the SHA of the PR branch HEAD.
=> chore: fix publish experimental hash

package.json
- Includes types in the package.json export
Fixes #354
Thanks for reporting the bug @talzion12
=> fix: include types in exports

CONTRIBUTING.md, renovate.json
Add renovate config to monitor test-harness version and upgrade flagd-testbed image.
Fixes #358
=> chore: renovate regex manager to monitor test-harness version

package-lock.json
Addresses vulnerabilities discovered by the NPM audit report.
decode-uri-component  <0.2.1
decode-uri-component vulnerable to Denial of Service (DoS) - https://github.com/advisories/GHSA-w573-4hg7-7wgq
fix available via `npm audit fix`
node_modules/decode-uri-component
json5  <1.0.2 || >=2.0.0 <2.2.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/json5
node_modules/tsconfig-paths/node_modules/json5
2 vulnerabilities (1 low, 1 high)
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>q
=> chore(deps): fix json5 vulnerability

CONTRIBUTING.md
- add signoff flag to contributing doc
=> docs: add signoff flag to contributing doc

.github/workflows/coverage.yml, .github/workflows/pr-checks.yaml, .github/workflows/release-please.yml, package.json, packages/server/package.json
- adds npm caching in all pipelines, with cache setup node takes 5s against 12s of before
Fixes #310
since 14 is now too old, we decided that 16 was the best version to avoid breaking changes
=> feat: add caching for pipelines

packages/client/src/client.ts, packages/client/src/index.ts, packages/client/src/open-feature.ts, packages/client/src/types.ts, rollup.config.mjs
:warning: This change only impacts the experimental web-sdk.
This includes an aliased, bundled version of `EventEmitter` so we have full control over that API/implementation, and consumers don't need the `events` dep for browsers.
We currently bundle [events](https://www.npmjs.com/package/events) (a browser polyfill for the node events API) into this package, but a provider author who wants to implement events in their provider would need to install that package as well. This removes the need for that. Interested in others' thoughts.
=> feat!: use bundled event emitter type

packages/client/integration/step-definitions/evaluation.spec.ts, packages/client/src/client.ts, packages/client/src/open-feature.ts, packages/client/src/types.ts, packages/server/src/client.ts, packages/shared/src/types.ts
Moves some events-related exports (unused by server API) from `/shared` to `/client`. We will eventually move some of these back, but for now I don't want these types to be seen by the server SDK (even if they are unused) since they are experimental.
=> fix: remove events exports from server

package-lock.json, packages/client/package.json, packages/server/package.json
use * for shared local dev dep so we don't have to manage it.
=> chore: wildcard for shared version

packages/client/test/open-feature.spec.ts
- adds checks for calls to the init/shutdown methods of a Provider
Fixes #406
=> test: add tests to provider init and shutdown

packages/client/src/client.ts, packages/client/src/open-feature.ts, packages/client/src/types.ts, packages/client/test/events.spec.ts
No functional changes. Refactor to how events are done, specifically with how they are maintained even across provider changes. This code is easier to understand IMHO, and also requires a few less structures/types.
Thanks to @RealAnna 's recent tests, we can do these changes with confidence :partying_face:
=> chore: refactor events

packages/client/src/client.ts, packages/client/test/client.spec.ts, packages/server/src/client.ts, packages/server/test/client.spec.ts, packages/shared/src/types.ts
- add support for flag metadata
Fixes #425
This feature is part of the recently released v0.6.0 of the OpenFeature spec.
Tests are included for both client and server.
=> feat: add support for flag metadata

package-lock.json, package.json, packages/client/e2e/step-definitions/evaluation.spec.ts, packages/client/src/client.ts, packages/client/src/no-op-provider.ts, packages/client/src/open-feature.ts, packages/client/src/types.ts, packages/client/test/client.spec.ts, packages/client/test/events.spec.ts, packages/client/test/open-feature.spec.ts, packages/server/src/client.ts, packages/server/src/open-feature.ts, packages/server/src/types.ts, packages/server/test/open-feature.spec.ts, packages/shared/src/type-guards.ts, packages/shared/src/types.ts
Implements named client support. #428 
Had to also add the provider status that is defined in the provider lifecycle and used for events.
Fixes #428 
This feature is part of the recently released v0.6.0 of the OpenFeature spec.
I would after this continue with the events and init/shutdown to round everything up.
Tests are included for both client and server.
=> feat: add named client support

jest.config.ts, package.json, packages/client/e2e/step-definitions/evaluation.spec.ts, packages/client/src/client.ts, packages/client/src/open-feature.ts, packages/client/src/types.ts, packages/client/test/events.spec.ts, packages/client/test/open-feature.spec.ts, packages/server/e2e/step-definitions/evaluation.spec.ts, packages/server/src/client.ts, packages/server/src/no-op-provider.ts, packages/server/src/open-feature.ts, packages/server/src/types.ts, packages/server/test/events.spec.ts, packages/server/test/open-feature.spec.ts, packages/shared/src/events.ts, packages/shared/src/index.ts, packages/shared/src/open-feature.ts, packages/shared/src/types.ts, packages/shared/test/events.spec.ts
Implements init/shutdown and events support from spec version 0.6.0.  #424  #434 #435 
Fixes #434 
Fixes #435 
Moved as much code as possible to the shared package.
Maybe we could even share some more code of the client.
Tests are included for both client and server.
=> feat: add init/shutdown and events

packages/client/test/open-feature.spec.ts, packages/server/test/open-feature.spec.ts, packages/shared/src/open-feature.ts
Providers that are bound to several named clients are closed if another provider is set for one of these clients.
This PR only closes providers if they are not used by any client.
Fixes #443 
Added tests for server and client.
=> fix: only shutdown providers that are not attached to any client

packages/client/e2e/step-definitions/evaluation.spec.ts, packages/client/e2e/step-definitions/setup.ts, packages/server/e2e/step-definitions/evaluation.spec.ts, packages/server/e2e/step-definitions/setup.ts
Both the server and client e2e tests run fine in the CI, but in some local scenarios the "deep imports" we used were causing issues with module resolution.
I've updated the e2e test to always import from the "top level" instead of the /src sub-directory in the test suite.
=> chore: import fixes to fix e2e tests

packages/client/test/events.spec.ts, packages/server/test/events.spec.ts, packages/shared/src/filter.ts, packages/shared/src/open-feature.ts
* fixed issues where named client wouldnt get events from a default provider
=> fix: named client events

packages/client/test/events.spec.ts, packages/server/test/events.spec.ts, packages/shared/src/open-feature.ts
* fix an issue where events would fail to run on the default provider anonymous client if the provider was changed
=> fix: events on anon provider/client

packages/client/src/client/open-feature-client.ts, packages/client/test/events.spec.ts, packages/server/src/client/open-feature-client.ts, packages/server/src/provider/provider.ts, packages/server/test/events.spec.ts, packages/shared/src/events/eventing.ts, packages/shared/src/events/index.ts, packages/shared/src/events/open-feature-event-emitter.ts, packages/shared/src/open-feature.ts, packages/shared/test/events.spec.ts
- adds type safety to the event emitter
Fixes #489 
The event emitter was split into two classes. `OpenFeatureEventEmitter` is meant to be used by developers working on OpenFeature. `InternalEventEmitter` is meant for use within the SDK. Unfortunately, the internal emitter is currently being exposed publically. This is because both the client and server SDKs expose the entire shared lib.
=> feat: typesafe event emitter

packages/client/src/open-feature.ts, packages/client/test/events.spec.ts, packages/server/src/open-feature.ts, packages/server/test/events.spec.ts, packages/shared/src/open-feature.ts
Fixes a race condition that prevents handlers added while their provider is initializing from running.
=> fix: race adding handler during init

packages/client/src/open-feature.ts, packages/client/test/evaluation-context.spec.ts
Fixes context propagation for the static-context-paradigm as found in #488.
Fixes #488
=> fix: onContextChanged not running for named providers

packages/shared/src/provider/provider.ts
In 3 event provider implementations, [flagd-java](https://github.com/open-feature/java-sdk-contrib/pull/361#pullrequestreview-1541468446), [go-feature-flag-web](https://github.com/open-feature/js-sdk-contrib/pull/474#discussion_r1274012627), and even my own implementation of flagd-js, authors have forgotten to properly implement `getState` (which means the SDK assumes the provider is already `READY` and doesn't run `initialize()`.)
This is an easy pitfall. To help with this, I'm adding doc.
We may be able to improve the interfaces to help with this, but I think this is a safe and helpful change for now.
Relates to: https://github.com/open-feature/java-sdk/pull/531
=> fix: provider js-doc improvments 

package-lock.json, package.json, packages/client/e2e/step-definitions/evaluation.spec.ts, packages/client/e2e/step-definitions/setup.ts, packages/client/test/open-feature.spec.ts, packages/server/e2e/step-definitions/evaluation.spec.ts, packages/server/test/open-feature.spec.ts, packages/shared/src/open-feature.ts
See here. We should only run initialize if `ProviderStatus` is `NOT_READY` to prevent duplicate calls to `initialize`, as we  [Java](https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/ProviderRepository.java#L107-L108) and [Go](https://github.com/open-feature/go-sdk/blob/main/pkg/openfeature/api.go#L173).
Most of this is test and formatting changes (I had to update the tests not to use the same object literal). The import change is the single line here.
Note: it's likely this will break _some_ providers that didn't implement `status`. I think the [flagd web provider](https://github.com/open-feature/js-sdk-contrib/blob/main/libs/providers/flagd-web/src/lib/flagd-web-provider.ts), [GoFF](https://github.com/open-feature/js-sdk-contrib/blob/main/libs/providers …
=> fix: only initialize NOT_READY providers

packages/server/README.md
- update the server-side readme to state that it's intended for use in node.js environments
Now that we have client and server SDK, it's important that we clearly denote what each SDK was decided for. Currently, we're only testing the node.js runtime, so I think it makes sense to explicitly state that at the top of the readme. We may support other runtimes in the future (e.g. Deno, Bun). If this happens, we can update the description with the additional runtimes.
Update the documentation to say Node.js instead of server-side JS.
=> docs: update server-side readme to explicitly mention node.js

.release-please-manifest.json, package-lock.json, package.json, packages/react/README.md, packages/react/package.json, packages/react/src/index.ts, packages/react/src/provider.tsx, packages/react/src/use-feature-flag.ts, packages/react/test/tsconfig.json, packages/react/tsconfig.json, release-please-config.json, rollup.config.mjs
This PR:
- adds all the necessary groundwork for a new react module in the monorepo (packaging, release, CI, etc)
- adds a _very_ limited implementation based on work by @moredip , see example in [README](https://github.com/open-feature/js-sdk/blob/a9104c1ca2a2fecd75b02e1d804a7bb984dd6d2d/packages/react/README.md)
Things to note:
- I've chosen NOT to bundle in the web-sdk directly into the react-sdk (which I could have done). Instead, the web-sdk is a peer dependency. Reasoning:
- NPM 16+ automatically downloads peer deps if missing, and otherwise uses the available peer if compatible
- Providers "don't care" whether they are used by the web-sdk, or the react-sdk, however, they all need a peerDependency on the web-sdk. If we bundled the web-sdk into the react-sdk automatically, it would …
=> feat: react sdk groundwork

packages/react/src/use-feature-flag.ts
This proposes to return the whole feature flag evaluation details from the react `useFeatureFlag` hook.
Only thing i am not sure if we should return an alias type for EvaluationDetails or as is is in this PR, the EvaluationDetails type.  Using an alias maybe like `type FeatureFlag<T> = EvaluationDetails<T>` would make clear that this may be extended later, even though we can still do it without having an alias now.
The hook becomes nicely usable as seen in the following.
```ts
const { value } = useFeatureFlag('feature-enabled', false);
```
=> feat(react-sdk): return flag evaluation details from hook

packages/client/README.md, packages/client/src/client/open-feature-client.ts, packages/client/test/client.spec.ts, packages/client/test/events.spec.ts, packages/server/README.md, packages/server/src/client/open-feature-client.ts, packages/server/test/client.spec.ts, packages/server/test/events.spec.ts, packages/shared/src/events/event-utils.ts, packages/shared/src/events/eventing.ts, packages/shared/src/events/index.ts, packages/shared/src/events/open-feature-event-emitter.ts, packages/shared/src/filter.ts, packages/shared/src/open-feature.ts, packages/shared/src/provider/provider.ts
* added the "STALE" provider state
* added "providerName" to EventDetails
* run handlers immediately if provider in corresponding state
* fixes a few lint issues
Fixes: https://github.com/open-feature/js-sdk/issues/562
Fixes: https://github.com/open-feature/js-sdk/issues/539
=> feat: STALE state, minor event changes

packages/client/README.md
Adds docs to JavaScript web-client sdk regarding flag evaluation flow and context.
Closes #570 
Mermaid diagrams were used but I'm not sure if they are currently supported.
=> docs: add web client docs

packages/client/src/open-feature.ts, packages/client/test/client.spec.ts, packages/client/test/events.spec.ts, packages/client/test/hooks.spec.ts, packages/client/test/open-feature.spec.ts, packages/server/src/open-feature.ts, packages/server/test/client.spec.ts, packages/server/test/events.spec.ts, packages/server/test/hooks.spec.ts, packages/server/test/logger.spec.ts, packages/server/test/open-feature.spec.ts, packages/shared/src/open-feature.ts
- adds support for clearing providers
Fixes #526 
We may want to consider adding a reset method that calls `clearHooks`, `clearProviders`, rests the logger, and clears event listeners. There are a few tests that use a hacky method to do this already.
=> feat: add support for clearing providers

.github/workflows/dco-merge-group.yml, .github/workflows/pr-checks.yaml, .github/workflows/release-please.yml
- add merge queue trigger to pr check action
- add dco merge queue workaround
`q
Enable merge queues in the repo.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
=> ci: update repo to support merge queues

packages/client/src/client/open-feature-client.ts, packages/client/src/events/index.ts, packages/client/src/events/internal/internal-event-emitter.ts, packages/client/src/events/open-feature-event-emitter.ts, packages/client/src/index.ts, packages/client/src/open-feature.ts, packages/client/test/events.spec.ts, packages/client/tsconfig.json, packages/server/src/client/open-feature-client.ts, packages/server/src/events/index.ts, packages/server/src/events/internal/internal-event-emitter.ts, packages/server/src/events/open-feature-event-emitter.ts, packages/server/src/index.ts, packages/server/src/open-feature.ts, packages/server/src/provider/in-memory-provider/in-memory-provider.ts, packages/server/test/events.spec.ts, packages/server/test/in-memory-provider.spec.ts, packages/server/tsconfig.json, packages/shared/src/events/generic-event-emitter.ts, packages/shared/src/events/index.ts, packages/shared/src/open-feature.ts, packages/shared/src/provider/provider.ts, packages/shared/test/events.spec.ts
Fixes: https://github.com/open-feature/js-sdk/issues/659
This PR fixes an issue created with [this change](https://github.com/open-feature/js-sdk/pull/650), which removed the `events` polyfill package from `@openfeature/core` where is wasn't always needed (see that issue for details). The problem was that we still imported `events` in the `@openfeature/core` module, but can't use the `events` bundled in the `@openfeature/web-sdk` since the bundled package there isn't accessible from imports in `@openfeature/core`.
This PR _**removes all imports of `events`**_ from `@openfeature/core`, and instead only imports types. Imports of `events` only now occur in the web-sdk (where it's bundled) and server-sdk (where it's made available by the node runtime), not in the common module.
Unfortunately …
=> fix: missing events bundled dep

packages/server/test/errors.spec.ts, packages/shared/src/errors/index.ts, packages/shared/src/errors/provider-not-ready-error.ts
Adds an Error class for the error code Provider Not Ready. To match the other error codes.
=> fix: add Provider Not Ready Error

packages/react/README.md
The documentation conditionally renders something if the returned value from the hook is truthy, but this implies that it is simply checking for the entirety of the `EvaluationDetails<T>` returned from `useFeatureFlag` which seems off since we will always get an object back according to the typings. It feel like it should be checking against the `.value` to conditionally render the elements.
=> chore: fix React SDK README.md to use the resolved value instead of the resolution details

packages/server/src/hooks/hook.ts, packages/server/test/hooks.spec.ts
- Updates the server-side before hook type to perform async work without modifying context.
Fixes #689
I added a test but the test runner isn't not validating types.
=> fix: type support for Promise<void> before hook

packages/client/src/client/open-feature-client.ts, packages/client/test/events.spec.ts, packages/server/test/events.spec.ts
* web-sdk handlers should run immediately if provider in matching state
* added tests for both server and client
Fixes: https://github.com/open-feature/js-sdk/issues/700
=> fix: handlers should run immediately

packages/client/src/client/client.ts, packages/client/src/client/open-feature-client.ts, packages/client/test/client.spec.ts
This is separate PR for a similar change [here](https://github.com/open-feature/js-sdk/pull/698).
I'm hesitant to spec this at the moment. I'm only implementing it in the client because it seems particularly useful for React.
=> feat: ability to get current provider state

packages/client/src/open-feature.ts, packages/client/test/evaluation-context.spec.ts, packages/shared/src/open-feature.ts
- adds the ability to manage named context in the web SDK
Fixes #685 
This change requires additions to the spec before it can be merged. I'll mark this PR as a draft until the spec has been updated.
I also noticed that we currently use the term "named clients" to describe the scoped providers. I believe this terminology is confusing and made writing the JSDocs difficult because the client name shouldn't be important when setting context. I think we should consider using the term "Provider Namespace". In my opinion, this more accurately describes the behavior and could be introduced in a non-breaking way.
=> feat: add evaluation context management to the web SDK

.release-please-manifest.json, jest.config.ts, package-lock.json, package.json, packages/nest/README.md, packages/nest/package.json, packages/nest/src/feature.decorator.ts, packages/nest/src/index.ts, packages/nest/src/open-feature.module.ts, packages/nest/test/open-feature-sdk.spec.ts, packages/nest/test/open-feature.module.spec.ts, packages/nest/test/test-app.ts, packages/nest/tsconfig.json, packages/nest/tsconfig.spec.json, packages/nest/typedoc.json, release-please-config.json
This is a first draft of a Nest.js SDK.
Currently it only handles injecting clients and feature flags.
I also added a context factory for the FeatureFlag decorators to be able to use request information for the execution context. 
Fixes #705 
@toddbaert maybe we can do it as we did with the React SDK, merge this fast and release as experimental to let people experiment and try out?
We will have to see if we want to stick with the injected feature flags being wrapped in an observable.
To me this feels the most idiomatic for Nest.js.
Tests for the current functionality are included.
=> feat: implement draft for a Nest.js SDK

packages/nest/src/open-feature.module.ts, packages/nest/test/fixtures.ts, packages/nest/test/open-feature-sdk.spec.ts, packages/nest/test/open-feature.module.spec.ts, packages/nest/test/test-app.ts
- Makes it possible to deactivate the global OF context interceptor
It currently supports passing a default context factory that is injected whenever the interceptor class is passed to `UseInterceptors`.
=> feat: add optout global context interceptors

packages/client/src/client/open-feature-client.ts, packages/client/src/events/events.ts, packages/client/src/events/index.ts, packages/client/src/events/internal/internal-event-emitter.ts, packages/client/src/events/open-feature-event-emitter.ts, packages/client/src/open-feature.ts, packages/client/src/provider/in-memory-provider/in-memory-provider.ts, packages/client/test/events.spec.ts, packages/client/test/in-memory-provider.spec.ts, packages/server/e2e/step-definitions/evaluation.spec.ts, packages/server/src/client/open-feature-client.ts, packages/server/src/events/events.ts, packages/server/src/events/index.ts, packages/server/src/events/internal/internal-event-emitter.ts, packages/server/src/events/open-feature-event-emitter.ts, packages/server/src/provider/in-memory-provider/in-memory-provider.ts, packages/server/test/in-memory-provider.spec.ts, packages/shared/src/events/event-utils.ts, packages/shared/src/events/eventing.ts, packages/shared/src/events/events.ts, packages/shared/src/events/generic-event-emitter.ts, packages/shared/src/open-feature.ts, packages/shared/src/provider/provider.ts, packages/shared/test/events.spec.ts
This PR:
- adds `PROVIDER_CONTEXT_CHANGED` events, which, in the static paradigm, can be used to inform the SDK that the flags should be re-evaluated (important for UI repaints in React, for instance (note this event is only available in the web-sdk)
- runs the associated `PROVIDER_CONTEXT_CHANGED` handlers if the provider's context handler function ran successfully or `PROVIDER_ERROR` handlers otherwise.
- adds associated tests
A decent amount of this is just typing magic to reduce duplicated code while making the new event only available in the web-sdk.
See: [associated spec change](https://github.com/open-feature/spec/pull/200) 
Fixes: https://github.com/open-feature/js-sdk/issues/729
=> feat: add PROVIDER_CONTEXT_CHANGED event (web-sdk only)

packages/client/src/client/open-feature-client.ts, packages/client/src/open-feature.ts, packages/client/test/evaluation-context.spec.ts
Fixed an issue with implementations of https://github.com/open-feature/js-sdk/pull/704 where the wrong context was passed to namespaced providers.
=> fix: wrong context passed to named providers

packages/client/src/open-feature.ts, packages/client/test/events.spec.ts, packages/shared/src/open-feature.ts
fixed an issue where some handlers would fail to run if the associated provider did not have a onContextChange method
=> fix: some handlers fail to run

packages/react/README.md
- fixes the example in react-sdk's REAMDE, add missing `EvaluationContext`.
=> chore: fix react-sdk REAMDE example, add missing `EvaluationContext`

packages/react/README.md, packages/react/src/use-feature-flag.ts
This PR brings the react SDK's evaluation API in-line with other SDKS. It does this by:
- adding flag value hooks for each type (these all use common code, with only differing generic args)
- adding flag details hooks for each type (again using common code)
- adding optional generic constraints for each
I think this is important before a non-experimental release for 2 reasons:
- it's consistent with our other JS components and other SDKs
- it fixes a potential bug if uses accidentally pass the wrong default type
:warning: This is a breaking change.
=> feat!: remove generic hook, add specific type hooks

package-lock.json, packages/nest/README.md, packages/nest/package.json
Adds `@nestjs/core` and rxjs version 8 to peer deps of nestjs-sdk.
Also fixes typos in README.
=> fix(nest): add peer deps for nestjs-core and rxjs 9

packages/shared/src/events/generic-event-emitter.ts, packages/shared/test/events.spec.ts
Fixes an issue where event handlers could be leaked if the same handler reference was added multiple times.
=> fix: event-handler leakage

package-lock.json, package.json, packages/client/tsconfig.rollup.json, packages/nest/tsconfig.rollup.json, packages/react/tsconfig.rollup.json, packages/server/tsconfig.rollup.json, packages/shared/tsconfig.rollup.json, rollup.config.mjs, tsconfig.json, tsconfig.rollup.json
A while back I added:
```json
"paths": {
"@openfeature/core": [ "./packages/shared/src" ]
},      
```
To the tsconfigs, which helped with local dev by always resolving `src/*` files from sibling packages instead of anything in their `dist/`.
It also had the nasty side-effect of causing our type bundling to include types from this package in it's output, causing duplicated artifacts and possible compiler issues. I've overridden this with a custom `tsconfig.rollup.json`.
Before this fix, the web/server SDK dists contained dupes of the stuff in shared:
```ts
import EventEmitter from 'events';
type FlagValueType = 'boolean' | 'string' | 'number' | 'object';
type PrimitiveValue = null | boolean | string | number;
type JsonObject = {
[key: string]: JsonValue;
};
type JsonArray = JsonValue[]; …
```
=> fix: removed duped core types

.github/workflows/lint-pr.yml
- adds the missing permissions so the linting action can create comments
Fixes #827 
Discovered while working on the python-sdk-contrib by @federicobond
https://github.com/open-feature/python-sdk-contrib/pull/38#discussion_r1498405835
=> ci: fix linting PR permissions

packages/client/src/client/client.ts, packages/client/src/client/open-feature-client.ts, packages/client/test/events.spec.ts, packages/server/src/client/client.ts, packages/server/test/events.spec.ts, packages/shared/src/events/eventing.ts, packages/shared/src/open-feature.ts
Before this change the `flagsChanged` prop on `EventDetails` was of type unknown for all event types, and a cast was needed.
After this change, `flagsChanged` is ONLY defined on `ProviderEvents.ConfigurationChanged`, where it should be, as (`string[] | undefined`) . In other words:
```typescript
client.addHandler(ProviderEvents.Ready, (details) => {
expect(details?.flagsChanged?.length).toEqual(1);  // does not compile
});
```
```typescript
client.addHandler(ProviderEvents.ConfigurationChanged, (details) => {
expect(details?.flagsChanged?.length).toEqual(1);  // DOES compile
});
```
Additionally, `flagsChanged` does not autocomplete for events handlers other than `ProviderEvents.ConfigurationChanged`.
=> fix: improve event handler types

packages/client/test/events.spec.ts, packages/server/test/events.spec.ts, packages/shared/src/events/eventing.ts
This is an addendum to https://github.com/open-feature/js-sdk/pull/816.
Since the `addHandler` overloads for the event types (`ProviderEvents.ConfigurationChanged` and `NotChangeEvents`) are mutually exclusive, it was impossible to iterate over them and pass the same function...
I had to add one more "base" overload that tolerated both. This doesn't reduce any of the nice type safety added in https://github.com/open-feature/js-sdk/pull/816, but allows users to iterate over `ProviderEvents` collections as seen in the new tests.
=> fix: allow iteration over all event types

packages/client/src/provider/in-memory-provider/in-memory-provider.ts, packages/react/package.json, packages/react/src/use-feature-flag.ts
This PR adds "suspend on reconciling" to the React SDK, in a manner [consistent with this spec](https://openfeature.dev/specification/sections/events#event-handlers-and-context-reconciliation).
When the SDK emits a PROVIDER_RECONCILING event, loaders are displayed until the CONTEXT_CHANGED event is emitted.
=> feat: suspend on RECONCILING, mem provider fixes

packages/client/src/events/open-feature-event-emitter.ts, packages/server/src/events/open-feature-event-emitter.ts, rollup.config.mjs
My rollup config was invalid, but clumsily working until a recent change in how we defined the event emitter type. The impact was the the bundled types for the web imported `from 'events'` instead of bundling it.
This PR fixes the mis-configuration (see comments).
Here is a screenshot showing the bundled types in the dist now (notice the import is gone and the emitter is in-lined, no other changes are present): 
In server, this type is available from node, so we DON'T need to bundle it, and in fact, SHOULD import it. This is easily done by importing it like `from 'node:events'`. I don't think it would be a problem if we bundled it anyway, but this is more correct.
Fixes: https://github.com/open-feature/js-sdk/issues/845
=> fix: correct rollup to bundle all but core

package-lock.json, package.json, packages/client/src/events/open-feature-event-emitter.ts, packages/shared/src/events/generic-event-emitter.ts
Fixes an issue where the `events` node polyfill does not comply to the `node:events` types.
When trying to use the web OpenFeatureEventEmitter the following error message comes up, describing that the `events` polyfill's EventEmitter is incompatible to `node:events` EventEmitter.
```
✘ [ERROR] TS2416: Property 'eventEmitter' in type 'OpenFeatureEventEmitter' is not assignable to the same property in base type 'GenericEventEmitter<ProviderEmittableEvents, Record<string, unknown>>'.
Type 'EventEmitter' is not assignable to type 'PlatformEventEmitter'.
Types of property 'addListener' are incompatible.
Type '(type: string | number, listener: Listener) => EventEmitter' is not assignable to type '(eventName: string | symbol, listener: (...args: any[]) => void) => PlatformEventEmitter'.
Types of …
```
=> feat: use EvenEmitter3 for web-sdk

.release-please-manifest.json, packages/client/package.json, packages/server/package.json, packages/shared/CHANGELOG.md, packages/shared/package.json
Releasing a 1.0 `@openfeature/core` version for better versioning/peer-dep management for consumers.
=> chore: release/use 1.0 core

packages/client/README.md, packages/server/README.md
Adds a blurb out peer deps and lib development, installation.
@beeme1mr I also added a bit about `--legacy-peer-deps` after the closure of https://github.com/open-feature/js-sdk/issues/834
=> docs: add peer dep explainer

packages/react/src/provider.tsx
Fixes a typing bug that makes domain/client required; these should be optional, consistent with other SDKs and the spec.
=> fix: make domain/client optional

packages/client/src/client/open-feature-client.ts, packages/client/test/hooks.spec.ts, packages/server/src/client/open-feature-client.ts, packages/server/test/hooks.spec.ts
Clients were incorrectly populating the hook context provider metadata field with metadata from the default provider instead of the one bound to the client.
=> fix: return metadata for the bound provider in hookContext

package-lock.json, packages/nest/package.json
Fixes CVE in transitive express dep with nest update.
see: https://nvd.nist.gov/vuln/detail/CVE-2024-29041
=> fix(deps): resolve CVE-2024-29041 with nest update

package-lock.json, packages/react/README.md, packages/react/package.json, packages/react/src/evaluation/use-feature-flag.ts, packages/react/src/index.ts, packages/react/src/query/index.ts, packages/react/src/query/query.ts
This PR adds a new `useFlag` hook. This hook:
- returns an object supporting a react "query-style" API with relevant properties: `const { value: newMessage, isError, reason, errorCode, isAuthoritative, type } = useFlag('new-message', true);`
- supports ergonomic generics: 
```
const { value: boolVal }: FlagQuery<boolean> = useFlag('bool-flag', true);
const { value: stringVal }: FlagQuery<string> = useFlag('string-flag', 'string');
const { value: objVal }: FlagQuery<{greeting: string}> = useFlag('obj-flag', { greeting: 'hi' });
```
- supports all the same options and features as other hooks (suspense, etc)
This PR fixes some type bugs as well, and adds to the readme.
DEPENDS ON: https://github.com/open-feature/js-sdk/pull/898
=> feat: query-style, generic useFlag hook

packages/react/src/common/options.ts
When I was adding the general `suspend` option as @lukas-reining suggested (a way to enable/disable all suspense features) I broke the default options. I found this writing tests in a different branch.
Tests for the entire SDK including this are incoming shortly (today), but this is a fix for the issue.
=> fix: default options (re-renders not firing by default)

jest.config.ts, package-lock.json, package.json, packages/react/src/provider/use-when-provider-ready.ts, packages/react/test/evaluation.spec.tsx, packages/react/test/options.spec.ts, packages/react/test/provider.spec.tsx, packages/react/test/test.utils.ts
This PR:
- brings react-sdk test coverage from 0% to ~95%
- adds DOM-based testing (tests based on asserting DOM entity states)
- tests for query-style, basic, and detailed evaluation APIs
- tests for suspense functionality and re-rendering on context change
- tests for some util functions and hooks
- `renderHook` tests for non suspending hooks
- fixes a bug where `useWhenProviderReady` didn't cause re-render after the provider is ready if suspense wasn't used (leading to an out-of-date return value for provider readiness)
=> fix: re-render w/ useWhenProviderReady, add tests

README.md, packages/react/README.md, release-please-config.json
- prompts a release of a non-experimental react-sdk
- updates README to point to React and NestJS SDKs
- removes version of peer deps from README (too brittle, point users to `package.json`)
- adds an FAQ question
=> chore: remove pre-release, update readme

packages/client/README.md, packages/nest/README.md, packages/server/README.md
- bump spec version badge to v0.8.0
The SDKs have been complimented with the latest spec release, but we neglected to bump the badge version.
=> chore: bump spec version badge to v0.8.0

packages/react/src/common/suspend.ts, packages/react/src/common/suspense.ts, packages/react/src/evaluation/use-feature-flag.ts, packages/react/src/provider/use-open-feature-client-status.ts, packages/react/src/provider/use-when-provider-ready.ts, packages/react/test/evaluation.spec.tsx, packages/react/test/provider.spec.tsx
- Add an internal `useOpenFeatureClientStatus()` function to make it slightly easier to keep track of the state of the current Client, and know when to suspend or not.
- Replaces the `suspend()` function with a `suspendUntilReady()` function. The `suspendUntilReady()`  function fires immediatly during the first render or when the component cannot render due to the client having changed status.
- Put the Client status and the feature flag details inside React states. This is required to make APIs like `startTransition` work properly with the library
Fixes #920
I built the application with `npm build`, then `npm pack`. I used the modified code on a local project to see if it fixed the issues.
I built projects in CodeSanbox that demonstrate the issues.
For Suspense: …
=> fix: delayed suspense causes "flicker"

packages/client/src/open-feature.ts, packages/client/src/provider/provider.ts, packages/client/test/events.spec.ts
- skips emitting a reconciling event for synchronous onContextChange operations
This will avoid unexpected component rerenders for synchronous onContextChange operations.
The spec states that the SDK may avoid emitting the `PROVIDER_RECONCILING` if a provider can reconcile synchronously.
https://openfeature.dev/specification/sections/events#event-handlers-and-context-reconciliation
=> fix: skip reconciling event for synchronous onContextChange operations

jest.config.ts, packages/client/src/client/open-feature-client.ts, packages/client/test/hooks.spec.ts, packages/server/src/client/open-feature-client.ts, packages/server/test/hooks.spec.ts, packages/shared/src/errors/index.ts
- runs error hook when provider returns reason error or error code
Fixes #925
Based on a conversation in Slack: https://cloud-native.slack.com/archives/C06E4DE6S07/p1714581197391509
=> fix: run error hook when provider returns reason error or error code

packages/client/src/client/internal/open-feature-client.ts, packages/client/src/open-feature.ts, packages/client/test/client.spec.ts, packages/client/test/open-feature.spec.ts, packages/server/src/client/internal/open-feature-client.ts, packages/server/src/open-feature.ts, packages/server/test/client.spec.ts, packages/server/test/open-feature.spec.ts
As discussed here https://github.com/open-feature/js-sdk/pull/750#discussion_r1450896230, we should not export `OpenFeatureClient` from the server and web SDK. The type used outside the SDK should be `Client`, which is also used in the public APIs like `OpenFeatureApi`.
The question is, if we should mark this as breaking. 
Technically it will break code that imports `OpenFeatureClient` instead of `Client`, but as @toddbaert said code using it  could also be seen as "used wrong" while being technically fine.
I am still leaning towards marking it as breaking, to be sure we are not breaking something that is technically fine, just because it is unintended use. But I could also live with non-beaking.
=> fix: remove export of OpenFeatureClient

.github/workflows/audit-pending-releases.yml, .github/workflows/coverage.yml, .github/workflows/pr-checks.yaml, .github/workflows/release-please.yml, package.json, packages/nest/README.md, packages/server/README.md, packages/server/package.json
Removes Node 16 as it is deprecated.
=> feat: remove node 16

packages/react/README.md, packages/react/src/common/options.ts, packages/react/src/evaluation/use-feature-flag.ts, packages/react/test/evaluation.spec.tsx, packages/react/test/provider.spec.tsx
This PR:
- inverts the suspense defaults (we now do not suspend by default, you have to add `suspend:true` in options)
- adds `useSuspenseFlag` (analogous to `useSuspenseXxx`) in other libraries, which behaves the same as `useFlag` with `{ suspend: true }`
- updates README (specifically encourages use use "query-style" hooks over type-specific hooks
- adds `@experimental` jsdoc marker to all suspense options and hooks
- associated tests
Things to consider:
- I did not add `useSuspense{Type}FlagValue` and `useSuspense{Type}FlagDetails` hooks; we could do this if we wanted, but IMO these are already not the primary APIs we want to push users toward in react - we want them to use the generic `useFlag` and `useSuspenseFlag` which return the react query interfaces.
Fixes: …
=> feat!: disable suspense by default, add suspense hooks

package-lock.json, packages/nest/README.md, packages/nest/package.json, packages/nest/src/feature.decorator.ts, packages/nest/test/test-app.ts
As discussed here [#750](https://github.com/open-feature/js-sdk/pull/750#discussion_r1450896230), renames `@FeatureClient` to `@OpenFeatureClient` which is possible since we merged #918.
=> feat!: rename FeatureClient decorator to OpenFeatureClient

packages/react/README.md, packages/react/src/provider/index.ts, packages/react/src/provider/test-provider.tsx, packages/react/src/provider/use-open-feature-client.ts, packages/react/test/provider.spec.tsx, packages/react/test/test-provider.spec.tsx
Adds some testing utilities, specifically an `<OpenFeatureTestProvider/>` react context provider.
See README for details.
=> feat: add test provider

packages/client/src/provider/in-memory-provider/in-memory-provider.ts, packages/client/test/in-memory-provider.spec.ts, packages/react/package.json, packages/react/src/provider/test-provider.tsx, packages/react/test/test-provider.spec.tsx, packages/react/test/test.utils.ts
Fixes an issues with the React `OpenFeatureTestProvider` where the provider was not ready until the next event loop tick when the `flagValueMap` was used.
Also removes the initialization in the client in-memory provider, since it was only doing some un-needed validation inconsistent with the server provider.
=> fix: race condition in test provider with suspense

package-lock.json, packages/shared/src/client/client.ts, packages/shared/src/provider/provider.ts, packages/shared/src/types/metadata.ts
- Updates the `Metadata` type to a `Record` so that Providers can provide more than just the `name` property as part of the `metadata`.
Conversation [here](https://cloud-native.slack.com/archives/C03J36ZP020/p1721747906370629).
=> feat: updated the Metadata type to allow for custom properties

.release-please-manifest.json, jest.config.ts, package-lock.json, package.json, packages/angular/.eslintrc.json, packages/angular/.gitignore, packages/angular/README.md, packages/angular/angular.json, packages/angular/jest.config.ts, packages/angular/package.json, packages/angular/projects/angular-sdk/.eslintrc.json, packages/angular/projects/angular-sdk/README.md, packages/angular/projects/angular-sdk/ng-package.json, packages/angular/projects/angular-sdk/package.json, packages/angular/projects/angular-sdk/src/lib/feature-flag.directive.spec.ts, packages/angular/projects/angular-sdk/src/lib/feature-flag.directive.ts, packages/angular/projects/angular-sdk/src/lib/open-feature.module.ts, packages/angular/projects/angular-sdk/src/public-api.ts, packages/angular/projects/angular-sdk/src/test/test.utils.ts, packages/angular/projects/angular-sdk/tsconfig.lib.json, packages/angular/projects/angular-sdk/tsconfig.lib.prod.json, packages/angular/projects/angular-sdk/tsconfig.spec.json, packages/angular/setup-jest.ts, packages/angular/tsconfig.json, packages/angular/tsconfig.spec.json, release-please-config.json
Adds an Angular SDK as discussed in #976.
It mainly provides directives that conditionally render based on flag value and provider state.
I did not inject any OpenFeature service or anything like that, as I think the directives will be the way to access feature flags in the templates, and the OpenFeature global API can be used directly in services. But I am not 100% sure on that one.
Happy to receive feedback and opinions :)
A small test app can be found here: https://github.com/open-feature/angular-test-app
This can be used with [yalc](https://github.com/wclr/yalc).
=> feat: Angular SDK

packages/angular/package.json
Fixes publishing of Angular SDK package by not removing the version scripts from the built package.json.
Also fixes SBOM generation by adding the angular subproject to workspaces.
=> fix: angular package publish

packages/angular/projects/angular-sdk/README.md
- fixes toc
- improve content nesting
This PR addresses some issues I noticed when adding the Angular docs to openfeature.dev.
=> docs(angular): improve angular readme layout

release-please-config.json
As discussed, I propose to remove the experimental from the Nest.JS SDK.
It is used in several orgs and the API works well there.
=> chore: remove experimental from Nest.JS SDK

packages/react/src/provider/context.ts, packages/react/src/provider/index.ts, packages/react/src/provider/provider.tsx, packages/react/src/provider/use-context-mutator.ts, packages/react/test/provider.spec.tsx
New hook for mutating context instead of using the global object
Fixes #968
=> feat: use mutate context hook

packages/angular/projects/angular-sdk/src/lib/feature-flag.directive.ts
Fixes a race condition when the directive is first rendered.
Initially the initialization code in the constructor before the `@Input`s were bound to the variables. 
This meant that in some cases providers were called with `undefined` as flag key, which most providers accept, but for flipt-web the engine paniced due to the value being `unit` instead of a string.
=> fix(angular): fix race condition on initialization

packages/react/package.json
- require web 1.3.0+ for tracking
=> chore: bump minimum web peer

packages/react/README.md
Fixes various issues with the React readme that's causing issues in openfeature.dev.
https://github.com/open-feature/openfeature.dev/pull/761
=> docs: fix typos, links, and format

packages/server/src/client/internal/open-feature-client.ts, packages/web/src/client/internal/open-feature-client.ts
- avoids using error codes as flow control during an evaluation
=> perf: avoid using exceptions for flow control

packages/web/package.json
- bumps OpenFeature core version to match the current release
This should have been automatically by the CI but it didn't work for some reason. I'll look into why after the issue is resolved.
https://github.com/open-feature/js-sdk/commit/fe3ad8eeb9219ff08ba287cab228016da0b88e88#diff-e35631c960979816b4b2bda7950788e968930fcaf2cf39b482ff23117cd13888R50
=> fix: update OpenFeature core version to 1.5.0

.github/workflows/release-please.yml
- add provenance statement to released artifacts 
Snippet from the NPM docs:
> You can generate provenance statements for the packages you publish. This allows you to publicly establish where a package was built and who published a package, which can increase supply-chain security for your packages.
It also adds a cool badge in NPM 😎 
- https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow
=> ci: add provenance statement to released artifacts

packages/react/README.md, packages/react/src/evaluation/use-feature-flag.ts, packages/react/test/evaluation.spec.tsx
Adds an improvement to the React SDK which supports re-renders if the [flags changed](https://open-feature.github.io/js-sdk/types/_openfeature_server_sdk.ConfigChangeEvent.html) array from a provider event is falsy.
Since some providers have no knowledge of flags which are changed, this allows them to support dynamic re-rendering by not defining this property. If the prop is null/undefined, we diff all flags... If the property is explicitly set to an empty array, that means no flags have changed and the React SDK skips all diff checks.
=> feat: re-render if flagsChanged is falsy

packages/server/README.md
- Fixes incorrect comment in the README for the Hook implementation's `after` method.
=> docs: fix comment in README for Hook’s after method

packages/server/src/client/internal/open-feature-client.ts, packages/server/test/client.spec.ts, packages/shared/src/provider/provider.ts, packages/web/src/client/internal/open-feature-client.ts, packages/web/test/client.spec.ts
- updates the context and trackingEventDetails on the tracking interface to not be optional since they're always supplied by the SDK.
This is a small QoL improvement for provider devs implementing the tracking interface.
The SDK still compiles, and the tests don't need to be modified.
=> refactor: improve track interface for providers

.github/workflows/pr-checks.yaml
- adds node 22 to the test matrix
Node 22 is the current active LTS version. We still should target Node 18 but test Node 22.
=> ci: add node 22 to test matrix

packages/server/src/client/internal/open-feature-client.ts, packages/web/src/client/internal/open-feature-client.ts
Fixes an issue where the error message was lost if a provider returned a resolution which had an error code (instead of throwing).
Frankly I don't think testing this is worth it. I debating making the second arg to this function `message: string | undefined` instead of `message?: string` (which would force a second arg to be set) but that would be breaking and we'd need to release a core v2 to avoid possible tsc issues in consumers, which I don't think is worth it ether.
=> fix: msg missing when providers return err resolutions

packages/angular/projects/angular-sdk/package.json, release-please-config.json
Release Angular SDK as non-experimental version as described in #1110 
Release-As: 0.0.10
Fixes #1110
=> chore(angular): update angular package to a non-experimental version

packages/react/src/evaluation/use-feature-flag.ts, packages/react/src/provider/use-open-feature-client-status.ts, packages/server/src/client/internal/open-feature-client.ts, packages/server/test/events.spec.ts, packages/shared/src/events/eventing.ts, packages/shared/src/open-feature.ts, packages/shared/test/events.spec.ts, packages/web/src/client/internal/open-feature-client.ts, packages/web/test/events.spec.ts
- adds an optional abort signal option to the `addHandler` API both globally and on the client.
- updates the React useEffect hook to leverage the abort signal
This change was inspired by [this blog](https://kettanaito.com/blog/dont-sleep-on-abort-controller). It allows us to use abort controllers to easily unregister event handlers. I've checked [MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) to confirm that we shouldn't have any compatibility issues.
We'll need to bump the min peer dependency versions when releasing to avoid issues.
There should be pretty good test coverage of this. Please let me know if you spot any gaps.
=> feat: add support for abort controllers to event handlers

packages/server/src/open-feature.ts, packages/server/test/open-feature.spec.ts, packages/web/src/open-feature.ts, packages/web/test/open-feature.spec.ts
- add a top-level method for accessing providers
While working on some improvements to the way Suspense works in the React SDK, I ran into a few scenarios were having access to the provider itself was important. I needed a way to confidently tell that a provider was the noop provider since it has special properties like never being in a ready state. There are a few ways could could achieve this but I noticed that the Java SDK [already has methods](https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java#L279) that expose the provider. It also allowed me to improve some of our existing tests.
Unit tests have been updated accordingly.
=> feat: add a top-level method for accessing providers

CODEOWNERS
Global maintainers approval should also work as a codeowner approval
=> chore: add global maintainers to codeowners

release-please-config.json
This proposes prompting the release of `@openfeature/react-sdk` 1.0.0.
My reasoning:
- as far as I know, there's no breaking changes on the horizon
- this is being used in production by multiple orgs
- it only depends on other 1.0+ deps
Please let me know what you think, especially if you have objections.
:warning: this will not release 1.0, but will mark the NEXT release of the react SDK as 1.0
=> chore: prompt release of react v1

jest.config.ts
Fixes issue where nest test suite was running using dist not source of server sdk.
=> chore: use server src not dist in nest tests

packages/server/README.md, packages/server/src/open-feature.ts, packages/web/README.md, packages/web/src/open-feature.ts
- Updates readme examples to include a try/catch around setProviderAndWait
- Improves the setProviderAndWait JS Doc
Fixes #1179
https://cloud-native.slack.com/archives/C0344AANLA1/p1745326882304199
=> docs: Clarify the behavior of setProviderAndWait

packages/nest/README.md, packages/nest/src/feature.decorator.ts, packages/nest/src/index.ts, packages/nest/src/require-flags-enabled.decorator.ts, packages/nest/src/utils.ts, packages/nest/test/fixtures.ts, packages/nest/test/open-feature-sdk.spec.ts, packages/nest/test/test-app.ts
-  Feature: Adds a `RequireFlagsEnabled` decorator to allow a simple, reusable way to block access to a specific controller or endpoint based on the value of a list of one, or many, boolean flags
- Discussions on the approach & implementation are welcome!
- Update OpenFeature NestJS docs to include new `RequireFlagsEnabled` decorator & usage examples
`npx jest --selectProject=nest`
=> feat: adds RequireFlagsEnabled decorator

packages/server/src/client/internal/open-feature-client.ts, packages/server/src/hooks/hook.ts, packages/server/test/hooks-data.spec.ts, packages/shared/src/hooks/hook-data.ts, packages/shared/src/hooks/hook.ts, packages/shared/src/hooks/hooks.ts, packages/shared/src/hooks/index.ts, packages/shared/test/hook-data-types.spec.ts, packages/shared/test/telemetry.spec.ts, packages/web/src/client/internal/open-feature-client.ts, packages/web/src/hooks/hook.ts, packages/web/test/hooks-data.spec.ts
- adds support for hook data in accordance to the spec
- adds optional type safety to the hook data keys and values
Fixes #1215
I had to add a bit more complexity in order to maintain support for existing hook implementations that used weakmaps.
Unit tests have been added
=> feat: add evaluation-scoped hook data

packages/web/package.json
- Implements a global (IIFE) build for the web.
- Adds support for global distribution via CDN by including `unpkg` and `jsdelivr` fields in `package.json`.
- The global build outputs to `dist/global/index.js`.
- The global bundle is exposed under the global name `OpenFeature`.
- Consider adding automated tests or validation for the global bundle.
- If this bundle should be included in a release checklist or CI, link the appropriate issue here.
1. Run `npm run build` and ensure `dist/global/index.js` is generated.
2. Serve the file locally or upload to a CDN and verify that `window.OpenFeature` is available in the browser console.
Trying to load OpenFeature as a first dependency before browser will resolve any modules.
=> feat(web-global-build): impl

packages/shared/src/telemetry/attributes.ts, packages/shared/src/telemetry/evaluation-event.ts, packages/shared/test/telemetry.spec.ts
- Makes OTEL evaluation event attributes compliant to OTEL Api types
=> fix: make OTEL evaluation event attribute types compliant to OTEL types
